In [1]:
import numpy as np

In [2]:
def binary_search(M,N):
    arr = M[0]
    
    a, b = 0, len(arr)-1
    
    while True:
        mid = (a+b) // 2
        
        if a == mid and mid == b:
            break
        
        if arr[mid] <= N:
            a = mid+1
        else:
            b = mid
            
    Mm = np.array(M[0][:mid+1])
    for i in M[1:]:
        Mm = np.vstack( (Mm,i[:mid+1]) )
        
    return Mm

In [18]:
M = np.array([ [10, 20, 30, 40, 50, 60, 70], [15, 25, 35, 45, 55, 65, 75], [20, 30, 40, 50, 60, 70, 80], [25, 35, 45, 55, 65, 75, 85 ] ])

In [11]:
M = np.array([ [10, 20, 30, 40], [15, 25, 35, 45], [27, 29, 37, 48], [32, 33, 39, 50] ]);

In [20]:
N = 35

print('look for',N,'\n\n0. start from')
print(M)

# step 1 exclude right half matrix
Mm = binary_search(M,N)
print('1. reduced to')
print(Mm)

# step 2 exclude lower half matrix
Mmm =  binary_search(Mm.T,N).T
print('2. reduced to')
print(Mmm)


# step 3 step down the matrix
i = 0
j = len(Mmm[0])-1
while True:
    print('3. start from',(i,j))
    
    if Mmm[i][j] == N:
        print(N,'found at',(i,j))
        break
    else:
        if i == len(Mmm)-1 or (j == 0 and Mmm[i+1][j] > N):
            print('not found')
            break
            
        if j == 0 or (j > 0 and Mmm[i+1][j] <= N):
            print('go down')
            i += 1
        else:
            print('go left')
            j -= 1

look for 35 

0. start from
[[10 20 30 40 50 60 70]
 [15 25 35 45 55 65 75]
 [20 30 40 50 60 70 80]
 [25 35 45 55 65 75 85]]
1. reduced to
[[10 20 30 40]
 [15 25 35 45]
 [20 30 40 50]
 [25 35 45 55]]
2. reduced to
[[10 20 30 40]
 [15 25 35 45]
 [20 30 40 50]
 [25 35 45 55]]
3. start from (0, 3)
go left
3. start from (0, 2)
go down
3. start from (1, 2)
35 found at (1, 2)
